version: 1

'survival.endkind.net':
  listenPort: 25565
  backendHost: '192.168.0.100'
  backendPort: 25565

'forge.endkind.net':
  listenPort: 25565
  backendHost: '192.168.0.101'
  backendPort: 25565
